import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import { createPostgresPool } from "./postgres.js";
import { migrateDatabaseSchema } from "./schema.js";
import { createMembershipRepository } from "./membershipRepository.js";
import { createKickActivitiesRepository } from "./kickActivitiesRepository.js";
import { createContentRepository } from "./contentRepository.js";
import { createGiveawayRepository } from "./giveawayRepository.js";
import { createApplicationRepository } from "./applicationRepository.js";
import { createTicketRepository } from "./ticketRepository.js";
import { createTemporaryVoiceRepository } from "./temporaryVoiceRepository.js";
import { purgeGuildOwnedData } from "./guildDataPurge.js";

const url = process.env.MEMBERSHIP_LIFECYCLE_TEST_DATABASE_URL;
test("PostgreSQL kick revokes activities atomically, preserves history and other tenants, and permanently retires old authority", { skip: !url }, async () => {
  const target = new URL(url!);
  assert.equal(target.pathname, "/guild_manager_membership_test");
  assert.ok(["localhost", "127.0.0.1", "[::1]"].includes(target.hostname));
  const pool = createPostgresPool(url!);
  const guild = `kick-activity-${randomUUID()}`, otherGuild = `${guild}-other`, character = `${guild}-character`;
  const membership = createMembershipRepository(pool), activities = createKickActivitiesRepository(pool), content = createContentRepository(pool), giveaways = createGiveawayRepository(pool);
  const registration = { discordGuildId: guild, discordUserId: "kicked", albionServer: "europe" as const, player: { id: character, name: "Activity Character" } };
  try {
    await migrateDatabaseSchema(pool);
    for (const id of [guild, otherGuild]) await pool.query("insert into discord_guild_lifecycle(discord_guild_id,status,guild_name,activated_at) values($1,'active',$1,now())", [id]);
    await membership.registerCharacter(registration);
    const party = (tenant: string, host: string) => content.createContent({ discordGuildId: tenant, sourceChannelId: "source", threadChannelId: randomUUID(), hostDiscordUserId: host, title: "Party", description: "", scheduledStartAt: null, roleLabels: ["DPS", "Heal"], approvalRequired: true });
    const hosted = await party(guild, "kicked"), historical = await party(guild, "kicked"), participating = await party(guild, "other"), untouched = await party(otherGuild, "kicked");
    await pool.query("update content_items set state='ended', ended_at=now() where discord_guild_id=$1 and content_id=$2", [guild, historical.content.contentId]);
    await pool.query("insert into content_signups(discord_guild_id,content_id,content_role_slot_id,discord_user_id) values($1,$2,$3,'kicked'),($1,$2,$4,'other')", [guild, participating.content.contentId, participating.slots[0].contentRoleSlotId, participating.slots[1].contentRoleSlotId]);
    await content.requestSignup({ discordGuildId: guild, contentId: hosted.content.contentId, discordUserId: "other", roleSlotId: hosted.slots[0].contentRoleSlotId });
    const giveaway = (tenant: string, host: string) => giveaways.create({ discordGuildId: tenant, channelId: "giveaways", originalMessageId: randomUUID(), creatorDiscordUserId: host, title: "Prize", description: "", drawAt: new Date(Date.now() + 86400000), winnerCount: 1 });
    const hostedGiveaway = await giveaway(guild, "kicked"), oldGiveaway = await giveaway(guild, "kicked"), sharedGiveaway = await giveaway(guild, "other"), untouchedGiveaway = await giveaway(otherGuild, "kicked");
    await pool.query("update giveaways set state='drawn', drawn_at=now() where discord_guild_id=$1 and giveaway_id=$2", [guild, oldGiveaway.giveawayId]);
    for (const id of [sharedGiveaway.giveawayId, oldGiveaway.giveawayId]) for (const user of ["kicked", "other"]) await pool.query("insert into giveaway_entries(giveaway_id,discord_guild_id,discord_user_id) values($1,$2,$3)", [id, guild, user]);
    const applicationClass = (await pool.query("insert into application_classes(discord_guild_id,name,outcome_type,albion_server,ticket_category_id,reviewer_role_id,created_by_discord_user_id) values($1,'Application','register_character','europe','category','reviewer','officer') returning application_class_id", [guild])).rows[0].application_class_id;
    const application = (await pool.query("insert into open_applications(application_class_id,discord_guild_id,applicant_discord_user_id,ticket_channel_id,submitted_character_name,albion_server,status,accepted_at,reviewer_discord_user_id) values($1,$2,'kicked','application-channel','Character','europe','accepted',now(),'historic-reviewer') returning application_id", [applicationClass, guild])).rows[0].application_id;
    const ticketClass = (await pool.query("insert into ticket_classes(discord_guild_id,name,ticket_category_id,reviewer_role_id,created_by_discord_user_id) values($1,'Ticket','category','reviewer','officer') returning ticket_class_id", [guild])).rows[0].ticket_class_id;
    const ticket = (await pool.query("insert into tickets(ticket_class_id,discord_guild_id,opener_discord_user_id,ticket_channel_id) values($1,$2,'kicked','ticket-channel') returning ticket_id", [ticketClass, guild])).rows[0].ticket_id;
    await pool.query("insert into temporary_voice_channels(discord_channel_id,discord_guild_id,owner_discord_user_id,base_channel_id) values($1,$2,'kicked','base')", [`${guild}-voice`, guild]);

    await membership.kickUser(guild, "kicked", [], "officer");
    assert.equal((await content.getContentSnapshot(guild, hosted.content.contentId))?.content.state, "cancelled");
    assert.equal((await content.getContentSnapshot(guild, historical.content.contentId))?.content.state, "ended");
    assert.equal((await content.getContentSnapshot(otherGuild, untouched.content.contentId))?.content.state, "unscheduled");
    assert.deepEqual((await content.getContentSnapshot(guild, participating.content.contentId))?.signups.map(row => row.discordUserId), ["other"]);
    assert.equal((await pool.query("select status from content_signup_requests where discord_guild_id=$1 and content_id=$2", [guild, hosted.content.contentId])).rows[0].status, "closed");
    assert.equal((await giveaways.getById(guild, hostedGiveaway.giveawayId))?.state, "cancelled");
    assert.equal((await giveaways.getById(guild, oldGiveaway.giveawayId))?.state, "drawn");
    assert.equal((await giveaways.getById(otherGuild, untouchedGiveaway.giveawayId))?.state, "open");
    assert.deepEqual(await giveaways.listRecordedParticipantIds(guild, sharedGiveaway.giveawayId), ["other"]);
    assert.deepEqual(await giveaways.listRecordedParticipantIds(guild, oldGiveaway.giveawayId), ["kicked", "other"]);
    assert.equal(await giveaways.recordDraw({ discordGuildId: guild, giveawayId: sharedGiveaway.giveawayId, participantReactions: [{ discordUserId: "kicked", emojiKeys: ["unicode:🎁"] }], winnerDiscordUserIds: ["kicked"] }), false);
    assert.equal((await giveaways.getById(guild, sharedGiveaway.giveawayId))?.state, "open");
    const app = await createApplicationRepository(pool).getOpenApplication(guild, application);
    assert.equal(app?.status, "accepted"); assert.equal(app?.channelStatus, "closed"); assert.ok(app?.accessRevokedAt); assert.equal(app?.reviewerDiscordUserId, "historic-reviewer");
    assert.equal((await createTicketRepository(pool).getTicket(guild, ticket))?.status, "closed");
    const voice = createTemporaryVoiceRepository(pool);
    assert.equal(await voice.getChannelByOwner(guild, "kicked"), undefined); assert.equal((await voice.listChannels(guild)).length, 1);
    const jobs = await activities.listPending(guild, "kicked");
    assert.deepEqual(jobs.map(job => job.kind).sort(), ["application", "content", "content", "giveaway", "giveaway", "ticket", "voice"]);
    await activities.complete(otherGuild, "kicked", jobs[0].cleanupId);
    assert.equal((await activities.listPending(guild, "kicked")).length, jobs.length);
    let access = (await membership.getMemberAccess(guild, "kicked"))!;
    assert.equal(await membership.markKickCleanupComplete(guild, "kicked", access.revision), false);
    await membership.kickUser(guild, "kicked", [], "officer");
    assert.equal((await activities.listPending(guild, "kicked")).length, jobs.length);
    for (const job of jobs) await activities.complete(guild, "kicked", job.cleanupId);
    access = (await membership.getMemberAccess(guild, "kicked"))!;
    assert.equal(await membership.markKickCleanupComplete(guild, "kicked", access.revision), true);
    await membership.registerCharacterAndAdoptOrphans({ ...registration, recovery: { expectedRegistrationRevision: null, expectedProfileRevisions: {}, verifiedMemberGroupIds: [], unavailableMemberGroupIds: [], ...await membership.getKickRecoverySnapshot(guild, "kicked", "europe", character) } });
    assert.equal((await membership.getMemberAccess(guild, "kicked"))?.blocked, false);
    for (const row of [hosted, historical]) assert.equal(await content.isHostAuthorityRevoked(guild, "kicked", row.content.contentId), true);
    assert.equal(await giveaways.isHostAuthorityRevoked(guild, "kicked", oldGiveaway.giveawayId), true);
    assert.equal(await giveaways.isHostAuthorityRevoked(otherGuild, "kicked", untouchedGiveaway.giveawayId), false);
    assert.equal(await createApplicationRepository(pool).markApplicationReopened(guild, application, "officer"), undefined);
    assert.equal(await createTicketRepository(pool).markTicketReopened(guild, ticket, "officer"), undefined);
    await pool.query("insert into temporary_voice_channels(discord_channel_id,discord_guild_id,owner_discord_user_id,base_channel_id) values($1,$2,'kicked','base')", [`${guild}-new-voice`, guild]);
    assert.equal((await voice.getChannelByOwner(guild, "kicked"))?.discordChannelId, `${guild}-new-voice`);
    assert.equal((await voice.listChannels(guild)).length, 2);
  } finally {
    for (const id of [guild, otherGuild]) await purgeGuildOwnedData(pool, id);
    await pool.query("delete from albion_characters where albion_character_id=$1", [character]);
    await pool.end();
  }
});
