import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import { createPostgresPool } from './postgres.js';
import { migrateDatabaseSchema } from './schema.js';
import { createMembershipRepository, CharacterRecoveryRequiredError, MembershipLifecycleConflictError, MembershipRecoveryVerificationUnavailableError } from './membershipRepository.js';
import { MEMBERSHIP_GRACE_MS } from './membershipLifecycleRepository.js';
import { purgeGuildOwnedData } from './guildDataPurge.js';
import { withLogChanges } from '../services/logFeed/events.js';

const url = process.env.MEMBERSHIP_LIFECYCLE_TEST_DATABASE_URL;
test('72-hour membership and registration lifecycles preserve, forfeit, and recover atomically in disposable PostgreSQL', { skip: !url }, async () => {
  const target = new URL(url!);
  assert.equal(target.pathname, '/guild_manager_membership_test');
  assert.ok(['localhost', '127.0.0.1', '[::1]'].includes(target.hostname));
  const pool = createPostgresPool(url!); const guild = `lifecycle-${randomUUID()}`; const user = 'member'; const character = `${guild}-character`;
  const repo = createMembershipRepository(pool);
  const ref = { discordGuildId: guild, albionServer: 'europe' as const, albionCharacterId: character };
  const registration = { discordGuildId: guild, discordUserId: user, albionServer: 'europe' as const, player: { id: character, name: 'Lifecycle Character' } };
  const now = new Date('2020-01-01T00:00:00Z'); const later = new Date(now.getTime() + MEMBERSHIP_GRACE_MS);
  const profiles = () => repo.listProfilesForCharacter(guild, ref.albionServer, character);
  const account = async () => (await pool.query('select * from character_accounts where discord_guild_id = $1 and albion_character_id = $2', [guild, character])).rows[0];
  const credit = async () => { await pool.query('update character_accounts set balance = 500 where discord_guild_id = $1', [guild]); };
  const evidence = async (verifiedMemberGroupIds: string[], unavailableMemberGroupIds: string[] = []) => ({
    expectedRegistrationRevision: (await repo.getRegistrationLifecycle(guild, ref.albionServer, character))?.revision ?? null,
    expectedProfileRevisions: Object.fromEntries((await profiles()).map(p => [p.memberGroupId, p.lifecycleRevision!])), verifiedMemberGroupIds, unavailableMemberGroupIds
  });
  try {
    await migrateDatabaseSchema(pool);
    const a = await repo.configureAlbionGuild({ discordGuildId: guild, albionServer: 'europe', albionGuildId: `${guild}-a`, albionGuildName: 'A', managed: true });
    const b = await repo.configureAlbionGuild({ discordGuildId: guild, albionServer: 'europe', albionGuildId: `${guild}-b`, albionGuildName: 'B', managed: false });
    await repo.upsertVerifiedCharacter('europe', registration.player);
    await withLogChanges(guild, () => repo.addOrphanProfile({ ...ref, memberGroupId: a.memberGroupId }));
    assert.equal(await account(), undefined, 'unregistered roster observations never open an account');
    assert.equal((await profiles())[0].entitlementPreserved, false);
    await repo.registerCharacter(registration);
    await withLogChanges(guild, () => repo.addRegisteredProfile({ ...ref, memberGroupId: a.memberGroupId, discordUserId: user }));
    await repo.addRegisteredProfile({ ...ref, memberGroupId: b.memberGroupId, discordUserId: user });
    await credit();
    const pa = (await profiles()).find(p => p.memberGroupId === a.memberGroupId)!;
    const departedA = await repo.markMembershipDeparted({ ...ref, memberGroupId: a.memberGroupId, lifecycleRevision: pa.lifecycleRevision }, now);
    assert.equal(departedA?.departureExpiresAt?.getTime(), later.getTime());
    assert.equal(await repo.markMembershipDeparted({ ...ref, memberGroupId: a.memberGroupId }, new Date(now.getTime()+1000)), undefined, 'repeat detection does not extend grace');
    assert.equal(await repo.expireMembershipDeparture({ ...ref, memberGroupId: a.memberGroupId }, departedA!.lifecycleRevision!, new Date(later.getTime()-1)), false);
    assert.equal(await repo.expireMembershipDeparture({ ...ref, memberGroupId: a.memberGroupId }, departedA!.lifecycleRevision!, later), true);
    assert.equal((await account()).balance, '500', 'other membership preserves balance');
    const pb = (await profiles())[0];
    const departedB = await repo.markMembershipDeparted({ ...ref, memberGroupId: b.memberGroupId, lifecycleRevision: pb.lifecycleRevision }, now);
    const recoveredB = await repo.restoreDepartedMembership({ ...ref, memberGroupId: b.memberGroupId }, departedB!.lifecycleRevision!);
    assert.equal(recoveredB?.memberGroupProfileId, pb.memberGroupProfileId, 'verified recovery retains the exact profile after the buffer');
    assert.equal(recoveredB?.discordUserId, user);
    assert.equal((await account()).balance, '500');
    assert.equal(await repo.expireMembershipDeparture({ ...ref, memberGroupId: b.memberGroupId }, departedB!.lifecycleRevision!, later), false, 'stale expiry cannot remove the recovered membership');
    const departedAgain = await repo.markMembershipDeparted({ ...ref, memberGroupId: b.memberGroupId, lifecycleRevision: recoveredB!.lifecycleRevision }, now);
    assert.equal(await repo.expireMembershipDeparture({ ...ref, memberGroupId: b.memberGroupId }, departedAgain!.lifecycleRevision!, later), true);
    assert.equal((await account()).balance, '0'); assert.equal((await account()).status, 'closed');
    await repo.addRegisteredProfile({ ...ref, memberGroupId: a.memberGroupId, discordUserId: user });
    assert.equal((await account()).status, 'open'); assert.equal((await account()).balance, '0');
    await credit();
    const departureSnapshot = await repo.getDiscordRegistrationSnapshot(guild, user);
    await repo.registerCharacter(registration); // Updates the row version while external absence verification is in flight.
    assert.equal((await repo.beginDiscordDeparture(guild, user, new Date(), departureSnapshot)).holds.length, 0);
    assert.equal((await repo.listRegisteredCharacters(guild)).length, 1, 'late absence evidence cannot orphan a newer registration');
    const held = await repo.beginDiscordDeparture(guild, user, new Date(), await repo.getDiscordRegistrationSnapshot(guild, user));
    assert.equal(held.characters.length, 1); assert.equal(held.holds.length, 1);
    assert.equal((await repo.listRegisteredCharacters(guild)).length, 0);
    assert.equal((await profiles())[0].registrationState, 'hold');
    await assert.rejects(repo.registerCharacter(registration), CharacterRecoveryRequiredError);
    assert.equal((await repo.beginDiscordDeparture(guild, user)).holds.length, 0);
    const staleEvidence = await evidence([a.memberGroupId]);
    await assert.rejects(repo.registerCharacterAndAdoptOrphans({ ...registration, recovery: await evidence([], [a.memberGroupId]) }), MembershipRecoveryVerificationUnavailableError);
    await withLogChanges(guild, async changes => {
      await repo.registerCharacterAndAdoptOrphans({ ...registration, recovery: staleEvidence });
      assert.ok(changes.some(change => change.kind === "registration"));
    });
    assert.equal((await account()).balance, '500');
    assert.equal(await repo.abandonRegistration(ref, held.holds[0].revision, new Date(Date.now()+MEMBERSHIP_GRACE_MS+1000)), false, 'stale expiry cannot delete recovered character');
    await assert.rejects(repo.registerCharacterAndAdoptOrphans({ ...registration, recovery: staleEvidence }), MembershipLifecycleConflictError);
    const oldTime = new Date(Date.now()-MEMBERSHIP_GRACE_MS-1000);
    const second = await repo.beginDiscordDeparture(guild, user, oldTime);
    await repo.registerCharacterAndAdoptOrphans({ ...registration, recovery: await evidence([a.memberGroupId]) });
    assert.equal((await account()).balance, '0', 'officer recovery after deadline cannot rescue forfeited value');
    assert.equal((await profiles()).length, 1, 'fresh verified membership is created atomically after expired membership removal');
    assert.equal((await profiles())[0].discordUserId, user);
    assert.equal((await account()).status, 'open');
    await repo.addRegisteredProfile({ ...ref, memberGroupId: a.memberGroupId, discordUserId: user });
    const third = await repo.beginDiscordDeparture(guild, user, oldTime);
    assert.equal(await repo.abandonRegistration(ref, third.holds[0].revision), true);
    await repo.addOrphanProfile({ ...ref, memberGroupId: a.memberGroupId });
    assert.equal((await profiles())[0].registrationState, 'abandoned');
    assert.equal((await profiles())[0].entitlementPreserved, false);
    assert.equal((await account()).status, 'closed');
    await assert.rejects(repo.registerCharacter(registration), CharacterRecoveryRequiredError);
    await repo.registerCharacterAndAdoptOrphans({ ...registration, recovery: await evidence([], [a.memberGroupId]) });
    assert.equal((await profiles())[0].lifecycleState, 'unregistered', 'unknown fresh roster observation is not misclassified as departure');
    assert.equal((await account()).status, 'closed', 'no positive membership evidence means no account reopened');
    await repo.registerCharacterAndAdoptOrphans({ ...registration, recovery: await evidence([a.memberGroupId]) });
    assert.equal((await profiles())[0].discordUserId, user); assert.equal((await account()).balance, '0');
    await repo.unregisterCharacter({ ...ref, discordUserId: user });
    assert.equal((await profiles())[0].lifecycleState, 'manual');
    assert.equal(await repo.getRegistrationLifecycle(guild, ref.albionServer, character), undefined);
    assert.ok(second.holds[0].revision !== third.holds[0].revision);
    await repo.registerCharacterAndAdoptOrphans({ ...registration, recovery: await evidence([a.memberGroupId]) });
    const snapshot = (await profiles())[0];
    const competing = await Promise.all([0, 1].map(() => repo.markMembershipDeparted({ ...ref, memberGroupId: a.memberGroupId, lifecycleRevision: snapshot.lifecycleRevision }, now)));
    assert.equal(competing.filter(Boolean).length, 1, 'concurrent same-evidence departures produce one transition');
    const changed = competing.find(Boolean)!;
    assert.equal(await repo.expireMembershipDeparture({ ...ref, memberGroupId: a.memberGroupId }, changed.lifecycleRevision!, later), true);
    assert.equal(await repo.expireMembershipDeparture({ ...ref, memberGroupId: a.memberGroupId }, changed.lifecycleRevision!, later), false);
    assert.equal((await pool.query("select count(*) as count from account_transactions where discord_guild_id=$1 and transaction_type='closure_adjustment'", [guild])).rows[0].count, '2', 'forfeiture adjustments are not duplicated by retry');
    await repo.addRegisteredProfile({ ...ref, memberGroupId: a.memberGroupId, discordUserId: user });
    await credit();
    const beforeAtomic = (await profiles())[0];
    const position = await repo.createGroupPosition({ discordGuildId: guild, memberGroupId: a.memberGroupId, name: 'Captain', discordRoleId: 'role' });
    await repo.appointGroupPosition(guild, position!.memberGroupPositionId, beforeAtomic.memberGroupProfileId);
    const appointmentsBefore = await repo.listGroupPositionAppointments(guild);
    const atomicDeparture = await repo.markMembershipDeparted({ ...ref, memberGroupId: a.memberGroupId, lifecycleRevision: beforeAtomic.lifecycleRevision }, now);
    const restored = await repo.restoreDepartedMembership({ ...ref, memberGroupId: a.memberGroupId }, atomicDeparture!.lifecycleRevision!);
    assert.equal(restored?.discordUserId, user);
    assert.equal(restored?.memberGroupProfileId, beforeAtomic.memberGroupProfileId);
    assert.equal((await account()).status, 'open'); assert.equal((await account()).balance, '500');
    assert.deepEqual(await repo.listGroupPositionAppointments(guild), appointmentsBefore, 'verified return retains appointments');
    assert.equal(await repo.restoreDepartedMembership({ ...ref, memberGroupId: a.memberGroupId }, atomicDeparture!.lifecycleRevision!), undefined);
    const beforeOfficer = (await profiles())[0];
    await repo.markMembershipDeparted({ ...ref, memberGroupId: a.memberGroupId, lifecycleRevision: beforeOfficer.lifecycleRevision }, now);
    await repo.registerCharacterAndAdoptOrphans({ ...registration, recovery: await evidence([a.memberGroupId]) });
    assert.equal((await profiles())[0].memberGroupProfileId, beforeAtomic.memberGroupProfileId, 'officer recovery does not forfeit a verified membership after its buffer');
    assert.equal((await account()).balance, '500');
  } finally {
    await purgeGuildOwnedData(pool, guild);
    await pool.query('delete from albion_characters where albion_character_id = $1', [character]);
    await pool.end();
  }
});
